### ISSUE TITLE
Still learning Android?

### ISSUE THREAD

**Issue by JaeW** [mgolokhov/mgolokhov.github.io#1]
Hey Maxim - I know DoDroid is dead, but I think you're still working on/learning Android from what I can from this repository?  

I took a break then a detour (Java was rusty so I did that) and am now back to Android.  Found a great Android course taught by the <a href="https://www.youtube.com/user/slidenerd">slidenerd</a> guy.

**Comment by mgolokhov** [comment]
Hi, why do you think it is dead? =(

**Comment by JaeW** [comment]
They're not offering the class anymore through Coursera?  Or did they revamp and relaunch it?

**Comment by mgolokhov** [comment]
I'm actively refactoring code to use Content Providers. At the same time writing [a blog](http://mgolokhov.github.io/content_providers/).
Added 222 questions...

**Comment by mgolokhov** [comment]
> They're not offering the class anymore through Coursera?

They stopped it after part 2. But there are some claims that is not the end =)

**Comment by mgolokhov** [comment]
You can check

 https://www.coursera.org/specializations/android-app-development

https://www.coursera.org/learn/android-programming

**Comment by JaeW** [comment]
Cool blog.  Interesting that the app development specialty no longer includes Porter.  

So you're going to market the app within that specialty?

**Comment by mgolokhov** [comment]
Did you finish https://www.udacity.com/course/developing-android-apps--ud853 ?

**Comment by mgolokhov** [comment]
In general we are building a quiz engine and as a bonus questions about Android development.
So it easier for new students to add content (for feature review).

**Comment by mgolokhov** [comment]
> I took a break then a detour (Java was rusty so I did that) 

I would recommend [java core](http://www.amazon.com/gp/product/0134177304/ref=pd_lpo_sbs_dp_ss_1?pf_rd_p=1944687722&pf_rd_s=lpo-top-stripe-1&pf_rd_t=201&pf_rd_i=0137081898&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=11Y4EF6SCYH35KMFVAAJ)

**Comment by JaeW** [comment]
I didn't, but I plan on returning to it.  I didn't love the way they taught.  I really needed a course that explains things from the ground up but that also constantly refers to the bigger picture.  Porter's class wasn't thorough enough, and the Udacity class has great info but doesn't teach it in an order which make sense (imho).  

 I have the Java down, but thanks for the suggestion.

**Comment by JaeW** [comment]
Congrats on the progress, btw!

**Comment by JaeW** [comment]
So did you take and/or finish the Udacity course?

**Comment by JaeW** [comment]
This is the Android course I'm working on now.

https://www.udemy.com/design-code-an-android-app-from-scratch/learn/v4/content

**Comment by mgolokhov** [comment]
> Congrats on the progress, btw!

Thx)))

Some courses are good in one topic, some in others.
It's good idea to study from multiple sources.

> So did you take and/or finish the Udacity course?

In the progress

**Comment by JaeW** [comment]
The multiple sources --- I totally agree!!  Back when I was working on my chemistry degree I had three physical chemistry books.  It's sort of like creating a 3-D mental understanding of a subject - even if the subject isn't physically 3-dimensional.

**Comment by JaeW** [comment]
So which Android source has been your favorite?

**Comment by mgolokhov** [comment]
http://developer.android.com/training/index.html =)

But there are many gaps, so you google, read stackoverflow, read any book you have, watch videos...

and study source code))))

**Comment by mgolokhov** [comment]
sametime add tricky questions to the quiz=)

**Comment by mgolokhov** [comment]
The best way to understand is to write about it.

**Comment by JaeW** [comment]
Here's what I like about the Udemy course (so far):

1)  Really, really in-depth coverage.  A lot he gives as assignments to go and read before you come back to the video, but a LOT of info that I have not learned (or seen mentioned) anywhere else.
2) He goes FAST.  The beauty of video is you can stop and rewind if you mentally "blink", so why do online teachers talk so slow?  
3) He's up on the latest Android tools, features and best practices
4) Everything he teaches is properly placed in the bigger, overall systemic understanding of Android development.

And no, I'm not getting paid to promote . . . .

**Comment by JaeW** [comment]
Write about it or teach it.  Totally agree.  

Anyway, didn't mean to sound like "my course is better."  Just wanted to mention it (it's not well promoted), and see how things are going with DoDroid.  Glad to hear all is well!  :-D

**Comment by mgolokhov** [comment]
It's ok, I bookmarked the course.
Any feedback and suggestions are appreciated.
One of the features in todo is to implement likes/dislikes, so students can show bad questions, and send small feedbacks.

**Comment by JaeW** [comment]
One thing about the course though, the design portion is a waste of time.  Both too high level and low level at the same time.  It's  very small portion of the overall class, though.

Out of curiosity, will you implement in multiple languages?

**Comment by mgolokhov** [comment]
May be as an exercise =)
UI in our case is easy one, but content...

**Comment by JaeW** [comment]
Yes, that makes sense.

**Comment by JaeW** [comment]
Cool to add questions about topics I'm learning in the Udemy course? To DoDroid's question DB, I mean.

**Comment by mgolokhov** [comment]
Any questions about Android )))

**Comment by JaeW** [comment]
Excellent!  I'll alter the form to allow for a write-in course source.  Okay with you?

**Comment by mgolokhov** [comment]
I think we can delete from form course parts.

**Comment by JaeW** [comment]
I may let you be the one to do that if okay.  I don't know how your scripts are written, and I don't want to cause an implosion.  Sorry.  This should be put in DoDroid's issues.  Will do that.

**Comment by mgolokhov** [comment]
I have just modified google form (you can edit as you like, it's an implosion-safe).

**Comment by JaeW** [comment]
Just saw that.  Dang you're fast.
